[project]
name = "first-steps"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "mamicaprepol", email = "mamidev99@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "fastapi[standard]>=0.141.1",
    "mypy>=2.3.1",
]

[tool.uv]
package = false
